/**
 * One-time script: Add full article body sections to all 10 topics' content JSON.
 * This makes ReadModeArticle render rich multi-section articles instead of just Summary + Key Facts.
 */
import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const ARTICLE_SECTIONS: Record<string, Array<{ id: string; title: string; type: string; body: string }>> = {
  'pythagorean-theorem': [
    {
      id: 'intro',
      title: 'Before Pythagoras',
      type: 'story',
      body: `Long before a Greek philosopher got the credit, the Pythagorean theorem was already old news. Babylonian clay tablets from 1800 BCE — that's nearly 4,000 years ago — contain lists of Pythagorean triplets carved into cuneiform. These weren't random numbers; they were used by architects and land surveyors to build perfectly right-angled walls and fields.\n\nBut here's the desi twist: India's Sulba Sutras, written between 800–500 BCE by Vedic scholars like Baudhayana, describe the theorem with remarkable precision. Baudhayana's text says: "The diagonal of a rectangle produces both areas which its length and breadth produce separately." That's a² + b² = c² — centuries before Pythagoras was even born.\n\nSo why does Pythagoras get all the fame? Because he (or his school) provided the first known logical proof. In ancient India, mathematics was practical and ritualistic — used for building fire altars of precise dimensions. In Greece, math was about pure logic and proof. Both approaches were brilliant, just different cultures asking different questions about the same truth.`
    },
    {
      id: 'theorem',
      title: 'The Theorem Itself',
      type: 'deep-dive',
      body: `Here's the statement that launched a thousand textbook chapters: In any right-angled triangle, the square of the hypotenuse (the longest side, opposite the right angle) equals the sum of squares of the other two sides. Mathematically: a² + b² = c².\n\nLet's make it concrete. Take a triangle with sides 3 cm, 4 cm, and 5 cm. Is it right-angled? Check: 3² + 4² = 9 + 16 = 25 = 5². Yes! These numbers — 3, 4, 5 — form a "Pythagorean triplet," and they're the most famous trio in mathematics.\n\nOther common triplets include 5-12-13, 8-15-17, and 7-24-25. Board exams love these — memorize them and you'll save precious minutes. There's even a formula to generate infinite triplets: for any integers m > n > 0, the triplet (m² - n², 2mn, m² + n²) always works.\n\nThe beauty of this theorem is its versatility. It works in reverse too — if a² + b² = c² for the three sides of any triangle, that triangle MUST have a right angle. This "converse" is equally powerful and appears in coordinate geometry, trigonometry, and even complex number proofs.`
    },
    {
      id: 'zing-moment',
      title: 'The Proof That Changed Math',
      type: 'zing-moment',
      body: `There are over 400 known proofs of the Pythagorean theorem — more than any other theorem in mathematics. Even a 12-year-old Albert Einstein came up with his own proof. But the most elegant one? It fits in a single diagram.\n\nImagine a large square with side length (a + b). Inside it, arrange four identical right-angled triangles (each with sides a, b, and hypotenuse c) so they form a smaller tilted square in the center. The area of the big square is (a + b)². The area of the four triangles is 4 × (½ab) = 2ab. The area of the inner square is c². So: (a + b)² = c² + 2ab. Expand the left side: a² + 2ab + b² = c² + 2ab. Cancel 2ab from both sides: a² + b² = c². Done.\n\nThat moment when the 2ab cancels and the theorem just appears — that's the ZING moment. No fancy calculus, no complicated algebra. Just geometry and a bit of clever arrangement. It's the kind of proof that makes you go "wait, that's it?" — and then you realize why mathematicians call it beautiful.\n\nJames Garfield, the 20th President of the United States, published his own unique proof in 1876 using a trapezoid. Yes, a sitting member of Congress proved a 2,000-year-old theorem for fun. Math really doesn't care about your job title.`
    },
    {
      id: 'real-world',
      title: 'Where You Use It Without Knowing',
      type: 'application',
      body: `Every time you open Google Maps, the distance calculation between two points uses the Pythagorean theorem (extended to latitude/longitude coordinates). That "5.2 km" on your screen? Pythagoras computed it.\n\nGame developers use it constantly. Want to check if two characters in a game are close enough to interact? Calculate the distance between them: √((x₂-x₁)² + (y₂-y₁)²). That's literally the Pythagorean theorem in coordinate form. Every collision detection system in every game you've ever played runs on this 2,500-year-old formula.\n\nArchitects use it to ensure walls are perfectly perpendicular. The "3-4-5 method" is still taught in construction training: measure 3 feet along one wall, 4 feet along the other, and if the diagonal is exactly 5 feet, your corner is a perfect 90°. Builders in ancient Egypt used knotted ropes with the same ratios to lay foundations for the pyramids.\n\nEven your phone's screen size is Pythagoras at work. When a phone is described as "6.5 inches," that's the diagonal measurement — calculated from width and height using a² + b² = c². The theorem is so deeply embedded in technology that removing it would break GPS, gaming, construction, astronomy, and basically... everything.`
    },
    {
      id: 'india',
      title: 'India Knew It First',
      type: 'india-connection',
      body: `The Sulba Sutras (800–500 BCE) are appendices to the Vedas that deal with the geometry of fire altar construction. The word "Sulba" means "cord" or "rope" — these were literally rope-and-stake geometry manuals.\n\nBaudhayana's Sulba Sutra contains the statement: "The diagonal of a rectangle produces the same area as the two sides produce separately." This is the Pythagorean theorem, stated clearly, roughly 300 years before Pythagoras.\n\nApastamba's Sulba Sutra goes further, listing specific Pythagorean triplets and providing methods to construct right angles for Vedic fire altars. These altars had to be built with astronomical precision because they were believed to be the interface between humans and gods. Get the geometry wrong, and the ritual wouldn't work — high stakes for high math!\n\nModern Indian mathematicians like Srinivasa Ramanujan continued this tradition. Ramanujan's work on number theory includes deep connections to Pythagorean-like equations. From Baudhayana to Ramanujan, India's mathematical DNA runs deep — and it all starts with the relationship between three sides of a triangle.`
    },
  ],

  'what-is-an-api': [
    {
      id: 'intro',
      title: 'The Chai Stall Analogy',
      type: 'story',
      body: `You walk up to a chai stall. You don't go behind the counter, light the stove, boil the water, or add the tea leaves yourself. Instead, you tell the chaiwala: "Ek cutting chai, kam sugar." He takes your order (request), makes the chai in the kitchen (server), and hands it to you through the counter (response). That counter? That's an API.\n\nAn API — Application Programming Interface — is a set of rules that lets one piece of software talk to another without knowing (or caring about) the internal details. Your phone's weather app doesn't contain a weather satellite. It sends a request to a weather API: "What's the temperature in Mumbai?" The API fetches the data from the server and sends back: "32°C, humid." Your app just displays it.\n\nThe magic of APIs is abstraction. You don't need to know how the chaiwala makes chai. You don't need to know what programming language a weather server uses. You just follow the rules — send the right request, get the right response. That's why APIs are called "contracts" in software engineering: both sides agree on the format, and everything just works.\n\nEvery app on your phone — Zomato, Ola, Paytm, Instagram — is actually a beautiful frontend talking to dozens of APIs behind the scenes. When you order biryani on Swiggy, APIs handle restaurant search, menu display, payment processing, driver assignment, and GPS tracking. You see one app; behind it are 50+ API calls working in harmony.`
    },
    {
      id: 'how-it-works',
      title: 'How APIs Actually Work',
      type: 'deep-dive',
      body: `Every API interaction has four parts: the endpoint (URL), the method (what you want to do), the headers (metadata), and the body (data you're sending).\n\nThe endpoint is like the stall's address: https://api.weather.com/v1/current?city=mumbai. The method tells the server what action to perform: GET (read data), POST (create something new), PUT (update existing data), DELETE (remove something). Think of it as the difference between asking the chaiwala for chai (GET), ordering a new special (POST), changing your order (PUT), or cancelling it (DELETE).\n\nHeaders carry metadata — your identity token (API key), the format you want (JSON or XML), language preference, etc. It's like showing your loyalty card or saying "bhaiya, thoda garam banana."\n\nThe response comes with a status code. 200 means "success — here's your data." 201 means "created successfully." 400 means "your request was wrong" (you ordered pasta at a chai stall). 401 means "show me your ID first." 404 means "we don't have that." 500 means "our kitchen is on fire." Learning these codes is like learning a new language — and it takes about 15 minutes.\n\nThe data format is almost always JSON (JavaScript Object Notation). A typical response looks like: { "city": "Mumbai", "temp": 32, "humidity": 78 }. Clean, readable, and universal — JSON is the lingua franca of the internet.`
    },
    {
      id: 'types',
      title: 'REST vs GraphQL vs gRPC',
      type: 'comparison',
      body: `REST (Representational State Transfer) is the most common API style. It uses standard HTTP methods and URLs. Each "resource" (user, product, order) gets its own URL. RESTful APIs are simple, predictable, and work everywhere. About 80% of public APIs are REST.\n\nGraphQL, created by Facebook in 2015, solves REST's biggest problem: over-fetching and under-fetching. With REST, if you want a user's name and their last 5 orders, you might need two separate API calls. With GraphQL, you send ONE query specifying exactly what you want, and the server returns exactly that — nothing more, nothing less. It's like telling the chaiwala: "Chai mein exact 2 spoon sugar, 100ml milk, aur ek elaichi" instead of accepting the default.\n\ngRPC (Google Remote Procedure Call) is built for speed. It uses Protocol Buffers instead of JSON, which makes it 5-10x faster for data serialization. It's used for internal microservice communication where milliseconds matter — think Google's internal services or Netflix's streaming infrastructure. Not human-readable, but blazing fast.\n\nWhen should you use what? REST for public APIs and simple CRUD. GraphQL when your frontend needs flexible data shapes (mobile apps that need different data than web apps). gRPC for internal service-to-service communication where speed is critical. Most Indian startups start with REST and add GraphQL when their mobile app needs diverge from their web app.`
    },
    {
      id: 'build',
      title: 'Build Your First API',
      type: 'hands-on',
      body: `The fastest way to build an API is with Node.js and Express. In 15 lines of code, you can have a working API:\n\nStep 1: Create a folder and run "npm init -y" then "npm install express". Step 2: Create index.js with a basic Express server. Define a GET route "/api/hello" that returns { message: "Namaste from my first API!" }. Step 3: Run "node index.js" and visit localhost:3000/api/hello in your browser. You just built an API.\n\nFrom there, you can add more routes: a POST route to accept data, connect to a database, add authentication with API keys, and deploy to a free platform like Vercel or Railway. The progression from "Hello World API" to a production API takes a weekend of focused learning.\n\nThe real learning happens when you consume other people's APIs. Try the OpenWeatherMap API — sign up for a free key, make a GET request, and parse the JSON response to show weather in your city. Then try the OMDB API to fetch movie data. Then Spotify's API to list your top tracks.\n\nPro tip: use Postman (or Thunder Client in VS Code) to test APIs before writing frontend code. Seeing the raw JSON response helps you understand the data structure, which makes writing the frontend 10x easier. Every professional developer tests in Postman first — it's not optional, it's essential.`
    },
  ],

  'upsc-preparation-guide': [
    {
      id: 'reality',
      title: 'The Reality Check',
      type: 'story',
      body: `Let's start with the numbers that no coaching institute puts on their banner: UPSC CSE 2024 had approximately 13 lakh applicants. About 14,000 cleared Prelims. About 2,800 cleared Mains. And roughly 1,000 got the final recommendation. That's a success rate of about 0.07%.\n\nBut here's what those numbers don't tell you: most of those 13 lakh didn't actually prepare seriously. They filled the form, maybe bought some books, and showed up hoping for the best. The real competition is among the 1-2 lakh serious aspirants. Against that pool, your odds are 1-in-100 to 1-in-200 — still tough, but not impossible.\n\nThe biggest myth about UPSC is that you need to be a genius. You don't. You need consistency, the right strategy, and 12-18 months of disciplined work. Toppers aren't superhuman — they're just people who showed up every day, read the newspaper every morning, and revised their notes every weekend. That's it. No magic formula, no secret sauce.\n\nThe second biggest myth: you need coaching. Many toppers have cracked UPSC without any coaching — using NCERT books, free YouTube lectures, and self-made notes. Coaching helps with structure and peer motivation, but it's not mandatory. What IS mandatory: a clear syllabus understanding, a time-bound plan, and brutal honesty about your weak areas.`
    },
    {
      id: 'syllabus',
      title: 'Understanding the Syllabus',
      type: 'deep-dive',
      body: `UPSC CSE has three stages. Prelims (June): two objective papers — General Studies (GS) and CSAT (aptitude). You need to clear both, but only GS marks count for ranking. Mains (September): nine papers including Essay, 4 GS papers, Optional subject, and 2 language papers. Interview (February-March): a 30-minute conversation that carries 275 marks.\n\nThe GS Prelims syllabus covers: History (ancient, medieval, modern), Geography (Indian + world), Polity (constitution, governance), Economy (basics, budget, schemes), Science & Technology, Environment, and Current Affairs. CSAT tests comprehension, logical reasoning, and math — it's qualifying (33%) so don't over-invest time here.\n\nThe Mains syllabus is deeper. GS-1 covers History, Culture, Society, and Geography in essay format. GS-2 is Governance, Polity, International Relations, and Social Justice. GS-3 is Economy, Science & Tech, Environment, Disaster Management, and Internal Security. GS-4 is Ethics — case studies and philosophical questions about integrity, empathy, and moral dilemmas.\n\nThe Optional Subject is your strategic weapon. Choose based on three criteria: syllabus overlap with GS (Public Administration and Geography have high overlap), availability of good resources, and your genuine interest. NEVER choose an optional just because a topper chose it. Check the last 5 years' average scores for each optional before deciding — some subjects consistently score lower due to strict evaluation.`
    },
    {
      id: 'strategy',
      title: 'The 18-Month Battle Plan',
      type: 'strategy',
      body: `Months 1-6 (Foundation): Read NCERT books cover to cover — Class 6-12 for History, Geography, Science, and Political Science. Don't take notes yet; just read for understanding. Start reading The Hindu or Indian Express daily — mark 5 articles relevant to GS. Begin one standard reference book per subject (Laxmikanth for Polity, Ramesh Singh for Economy).\n\nMonths 7-12 (Deep Dive): Start making short, revision-friendly notes. Begin your Optional subject seriously. Start answer writing practice — write at least 3 answers daily in 200 words within 7 minutes each. Join a test series for Prelims practice. This is where most aspirants fail: they keep reading but never practice writing.\n\nMonths 13-18 (Revision & Testing): Stop reading new material. Revise your notes cyclically — every topic should be revised at least 3 times. Give full-length mock tests weekly. Analyze every mock — understanding WHY you got a question wrong teaches more than reading new content. Focus on current affairs compilations.\n\nThe daily routine that works: 6 AM wake up → newspaper (1 hour) → subject study (3 hours) → lunch + rest → answer writing (2 hours) → optional (2 hours) → current affairs (1 hour) → revision (1 hour) → sleep by 11 PM. 10 productive hours daily is the sweet spot — anything more leads to burnout by month 6.`
    },
    {
      id: 'chanakya-moment',
      title: 'What Chanakya Would Tell You',
      type: 'zing-moment',
      body: `Chanakya's Arthashastra says: "Before you start any work, always ask yourself — Why am I doing it? What might the results be? Will I be successful? Only when you think deeply and find answers to these questions, proceed." This is the ZING moment for every UPSC aspirant.\n\nMost aspirants start preparation because of family pressure, societal prestige, or simply because they don't know what else to do with an Arts/Humanities degree. These motivations die within 3 months. The ones who crack it have a deeper reason — they want to serve in education policy, or fix water management, or reform the police system. Find your "Why" before you open a single book.\n\nChanakya also wrote: "A person should not be too honest. Straight trees are cut first." In UPSC context, this means: don't reveal your preparation gaps to everyone. Don't announce your attempt number. Don't let discouraging relatives sabotage your focus. Strategic silence is a weapon.\n\nAnd finally, the most Chanakya-relevant truth about UPSC: "The biggest guru is your own mind." The topper's reading list won't work for you if your learning style is different. Some people learn by reading, others by writing, others by teaching concepts aloud. Discover your style in month 1 — it saves you 6 months of inefficient study later.`
    },
    {
      id: 'resources',
      title: 'Free Resources That Actually Work',
      type: 'resources',
      body: `For books: Laxmikanth's Indian Polity (the UPSC bible — buy this one), Ramesh Singh's Indian Economy, Spectrum's Modern Indian History. For everything else, NCERTs are genuinely enough for the foundation phase.\n\nFor current affairs: The Hindu newspaper (free online — read the editorial and national pages), PRS Legislative Research (the best free resource for understanding Bills, Acts, and Parliament proceedings), PIB (Press Information Bureau — government's own updates, straight from source).\n\nFor answer writing: UPSC's own past year question papers are free on upsc.gov.in. Download the last 10 years of Prelims and Mains. Attempting these is the most honest reality check you can give yourself. Also: Mrunal.org has incredible free lectures on Economy and Geography on YouTube.\n\nFor test series: Many platforms offer free mock tests for Prelims — take at least 2-3 from different sources to see different question styles. The paid test series (ForumIAS, Vision IAS, Insights) cost around Rs 3,000-5,000 and are worth it for Mains answer evaluation.\n\nOne underrated resource: NIOS (National Institute of Open Schooling) study material. It's free, written in simpler language than NCERTs, and covers the same UPSC topics. Perfect for subjects where NCERTs feel too dense. Everything you need to crack UPSC is available for under Rs 5,000 total. The coaching industry doesn't want you to know that.`
    },
  ],

  'how-black-holes-work': [
    {
      id: 'death-of-star',
      title: 'The Death of a Star',
      type: 'story',
      body: `Every black hole begins as a star — but not just any star. Only stars with masses roughly 20-25 times our Sun's mass end up as black holes. These are the cosmic heavyweights, burning through their nuclear fuel at a furious pace.\n\nA star's life is a constant battle between two forces: gravity pulling inward and nuclear fusion pushing outward. For millions of years, fusion wins — hydrogen atoms smash together to form helium, releasing enormous energy (this is what makes the Sun shine). But eventually, the star runs out of hydrogen. It starts fusing helium into carbon, then carbon into neon, neon into oxygen, oxygen into silicon, and finally silicon into iron.\n\nIron is the dead end. Fusing iron doesn't release energy — it absorbs it. Within seconds (literally), the star's core collapses. The outer layers crash inward at 70,000 km per second, bounce off the incompressible core, and explode outward as a supernova — one of the most violent events in the universe, briefly outshining an entire galaxy.\n\nWhat's left behind depends on the original star's mass. If the remnant core is 1.4-3 solar masses, it becomes a neutron star (incomprehensibly dense — a teaspoon weighs a billion tons). If it's more than 3 solar masses, not even neutron degeneracy pressure can stop the collapse. Gravity wins completely. The core crushes into a single point of infinite density — a singularity. A black hole is born.`
    },
    {
      id: 'event-horizon',
      title: 'The Point of No Return',
      type: 'deep-dive',
      body: `The event horizon is not a physical surface. It's an invisible boundary — the distance from the singularity at which the escape velocity equals the speed of light. Since nothing can travel faster than light, anything that crosses the event horizon can never come back. Not light, not information, not even your regrets.\n\nThe radius of the event horizon is called the Schwarzschild radius, named after Karl Schwarzschild who calculated it in 1916 (while serving in WWI, because physicists are a different breed). The formula is elegant: Rs = 2GM/c², where G is the gravitational constant, M is the mass, and c is the speed of light. For our Sun, the Schwarzschild radius would be about 3 km. For Earth, it's just 9 millimeters.\n\nHere's what's truly mind-bending: from the outside, if you watched someone fall into a black hole, you'd see them slow down and gradually freeze at the event horizon, their image getting redder and dimmer until they fade away. But from the falling person's perspective, they'd cross the event horizon without even noticing — there's no sign, no wall, no sensation. They simply pass a point beyond which there's no return. The universe looks normal from inside looking out; it's the outside that can never see you again.\n\nNear (but outside) the event horizon, something extraordinary happens called "spaghettification." The gravitational pull on your feet is significantly stronger than on your head, stretching your body into a long thin strand — like a noodle. The technical term is "tidal forces," but spaghettification sounds exactly as painful as it is.`
    },
    {
      id: 'time-dilation',
      title: 'When Time Itself Bends',
      type: 'zing-moment',
      body: `Here's the ZING moment: time is not constant. Near a black hole, time literally runs slower compared to time far away from it. This isn't science fiction — it's Einstein's General Theory of Relativity, confirmed by experiments with atomic clocks on airplanes and GPS satellites.\n\nImagine two twins: one stays on Earth (let's call her Priya), the other orbits near a black hole (let's call her Isha). If Isha spends what feels like one year near the black hole, she might return to find Priya has aged 10 years, or 100 years, or even millions of years — depending on how close she got to the event horizon. This is real physics. Christopher Nolan's Interstellar showed this exactly: Cooper spent hours on a planet near a black hole while decades passed on Earth.\n\nGPS satellites already account for time dilation. They orbit at high speed (special relativity: time slows) but at high altitude where gravity is weaker (general relativity: time speeds up). The net effect means satellite clocks run about 38 microseconds faster per day than ground clocks. Without correcting for this, GPS would drift by 10 km daily. Your daily commute navigation literally depends on Einstein being right about time bending near mass.\n\nThe philosophical implication is staggering: there is no universal "now." The present moment for you is not the same as the present moment for someone near a black hole. Time is personal. The universe doesn't have a master clock — just local rhythms shaped by gravity and motion.`
    },
    {
      id: 'types',
      title: 'Stellar vs Supermassive vs Primordial',
      type: 'comparison',
      body: `Black holes come in three sizes, and the differences are staggering. Stellar black holes (5-100 solar masses) are formed from dying stars, as we discussed. They're "small" — a stellar black hole might be just 30 km across. The Milky Way alone contains an estimated 100 million of them, most invisible and harmless.\n\nSupermassive black holes are monsters — millions to billions of solar masses. Every large galaxy has one at its center. Our Milky Way's supermassive black hole, Sagittarius A* (pronounced "A-star"), weighs about 4 million solar masses. M87's supermassive black hole — the first ever photographed in 2019 — is 6.5 billion solar masses. How do they get so big? Scientists believe they grow by consuming gas, dust, and smaller black holes over billions of years, though the exact growth mechanism is still debated.\n\nThen there are theoretical primordial black holes — tiny ones that may have formed in the ultra-dense conditions right after the Big Bang. These could be as small as an atom yet weigh as much as a mountain. Stephen Hawking proposed that primordial black holes might actually evaporate over time through "Hawking radiation" — a quantum effect where particles escape from near the event horizon. If they exist, they could explain dark matter, one of the biggest mysteries in physics.\n\nAn intermediate class (100-100,000 solar masses) has also been theorized but rarely confirmed. In 2021, astronomers found strong evidence for one in a globular star cluster — it's an active area of research.`
    },
    {
      id: 'india',
      title: 'ISRO and Black Hole Research',
      type: 'india-connection',
      body: `India's contribution to black hole research is bigger than most people know. ISRO's AstroSat, launched in 2015, is India's first dedicated multi-wavelength space observatory. It has detected X-ray emissions from black holes in binary star systems, helping map how black holes consume matter from companion stars.\n\nIn 2021, Indian astronomers at the Aryabhatta Research Institute of Observational Sciences (ARIES) in Nainital discovered one of the most distant and ancient black holes — a quasar powered by a supermassive black hole that existed when the universe was only 1.3 billion years old. Finding such massive black holes so early in cosmic history challenges existing models of how black holes grow.\n\nThe Indian pulsar timing array (InPTA) project, involving multiple Indian research institutions, is part of a global effort to detect gravitational waves from merging supermassive black holes. These waves ripple through spacetime and can be detected by precisely timing the signals from distant pulsars. India's Giant Metrewave Radio Telescope (GMRT) near Pune — one of the world's largest radio telescope arrays — plays a crucial role in this.\n\nA fun fact: Subrahmanyan Chandrasekhar (Chandra), the Indian-American astrophysicist, calculated the maximum mass a white dwarf star can have before collapsing — the "Chandrasekhar limit" of 1.4 solar masses. This work, which won him the 1983 Nobel Prize, is foundational to understanding how stellar black holes form. NASA's Chandra X-ray Observatory is named after him.`
    },
  ],

  'why-do-we-dream': [
    {
      id: 'midnight',
      title: 'What Happens at 3 AM',
      type: 'story',
      body: `Every night, you go to a private cinema. The screen is behind your closed eyes, the director is your subconscious mind, and the script is written from fragments of your memories, fears, desires, and that random YouTube video you watched at 2 PM. Welcome to dreaming.\n\nSleep isn't a uniform shutdown — it cycles through stages. You start with light sleep (Stage 1), move to deeper sleep (Stages 2 and 3), and then enter REM (Rapid Eye Movement) sleep — the dream stage. Your first REM period starts about 90 minutes after falling asleep and lasts maybe 10 minutes. As the night goes on, REM periods get longer — the last one, usually around 3-5 AM, can last 30-45 minutes. This is when the most vivid, narrative-heavy dreams happen.\n\nDuring REM sleep, your brain is almost as active as when you're awake. Your eyes dart back and forth (hence "rapid eye movement"), your heart rate increases, and your breathing becomes irregular. But your body is paralyzed — a safety mechanism called "atonia" that prevents you from physically acting out your dreams. When this mechanism fails, people sleepwalk or thrash in bed.\n\nHere's the wildest part: you dream 4-6 times per night but forget about 95% of your dreams within 5 minutes of waking. The reason? During REM sleep, the brain chemical norepinephrine — critical for forming new memories — is at its lowest level. Your brain is essentially watching a movie without pressing "record." The dreams you DO remember are usually the ones from the last REM cycle, interrupted by your alarm.`
    },
    {
      id: 'science',
      title: 'The Neuroscience of Dreams',
      type: 'deep-dive',
      body: `Modern neuroscience has several competing theories about why we dream, and the honest answer is: we're not entirely sure. But the leading theories are fascinating.\n\nThe Memory Consolidation Theory says dreams help your brain sort through the day's experiences, strengthening important memories and discarding irrelevant ones. Studies show that people who sleep (and dream) after learning a new skill perform significantly better the next day. Your brain literally practices while you sleep.\n\nThe Threat Simulation Theory, proposed by Finnish neuroscientist Antti Revonsuo, suggests dreams evolved as a survival mechanism. By simulating threatening scenarios (being chased, falling, failing an exam), your brain rehearses responses to dangers in a safe environment. This explains why negative emotions — fear, anxiety, embarrassment — dominate in dreams more than positive ones.\n\nThe Emotional Processing Theory proposes that dreams help regulate emotions. People experiencing grief, breakup, or trauma often have intense dreams about the event. The theory suggests REM sleep strips the emotional charge from memories while preserving the content. You remember the event but it stops hurting as much. This is why "sleeping on it" genuinely helps with emotional problems.\n\nThe most recent theory, the Overfitted Brain Hypothesis (2021), compares the brain to a machine learning model. Just as AI needs random noise during training to avoid overfitting to training data, dreams inject random neural activation to keep the brain flexible and generalizable. Dreams, in this view, are your brain's version of data augmentation.`
    },
    {
      id: 'lucid',
      title: 'Lucid Dreaming — Controlling the Movie',
      type: 'zing-moment',
      body: `Imagine watching a dream and suddenly realizing: "Wait, this isn't real. I'm dreaming." And then, instead of waking up, you stay in the dream — and take control. You can fly, teleport, talk to dream characters, or change the entire scenery. That's lucid dreaming, and it's scientifically verified.\n\nBrain scans of lucid dreamers show activation in the prefrontal cortex — the brain's executive control center — which is normally shut down during regular REM sleep. It's as if the "rational manager" briefly wakes up inside the dream, while the "creative director" keeps running the show. The result: conscious awareness inside an unconscious process.\n\nAbout 55% of people have had at least one lucid dream naturally. But you can train yourself to have them. The most reliable technique is called MILD (Mnemonic Induction of Lucid Dreams): before falling asleep, repeat "next time I'm dreaming, I will realize I'm dreaming." During the day, perform "reality checks" — try pushing your finger through your palm, or read text (in dreams, text is unstable and keeps changing). These habits carry into dreams and trigger lucidity.\n\nHere's the ZING part: lucid dreaming isn't just a party trick. Researchers at Stanford have used it to help people overcome nightmares, practice physical skills (athletes visualizing performance), and even study consciousness itself. The question "what is awareness?" might ultimately be answered by people who can be conscious while unconscious.`
    },
    {
      id: 'theories',
      title: 'Freud vs Jung vs Modern Science',
      type: 'comparison',
      body: `Sigmund Freud (1900) believed dreams are "the royal road to the unconscious." According to Freud, every dream is a disguised wish fulfillment — your repressed desires manifest as symbolic images. Dreaming of flying? Desire for freedom. Dreaming of water? Hidden emotions. Freud's approach was creative but largely unfalsifiable — you can interpret anything to support the theory.\n\nCarl Jung (1916) agreed that dreams access the unconscious but rejected Freud's obsession. Jung believed dreams tap into a "collective unconscious" — a shared mental reservoir of symbols (archetypes) common to all humans. The wise old man, the great mother, the shadow self — these appear in dreams across cultures. Jung saw dreams as messages from the self, guiding personal growth.\n\nModern neuroscience is less romantic. The Activation-Synthesis Hypothesis (Hobson & McCarley, 1977) argues dreams are just the brain's attempt to make sense of random neural firings during sleep. There's no hidden meaning — your prefrontal cortex receives random signals from the brainstem and constructs a narrative because that's what brains do. It's like seeing shapes in clouds.\n\nThe truth is probably somewhere in between. Random neural activation provides the raw material, but emotional significance determines which content gets amplified. Your brain isn't sending you coded messages, but it IS processing what matters to you. The dream about failing an exam isn't a prediction — it's your brain stress-testing your anxiety circuits.`
    },
    {
      id: 'india',
      title: 'Swapna Shastra — Indian Dream Science',
      type: 'india-connection',
      body: `India has one of the world's oldest documented traditions of dream analysis. The Mandukya Upanishad (possibly 7th century BCE) describes four states of consciousness: Vaishvanara (waking), Taijasa (dreaming), Prajna (deep sleep), and Turiya (pure consciousness beyond the three). This framework predates Freud's conscious/unconscious model by over 2,500 years.\n\nSwapna Shastra (the science of dreams) appears in texts like the Brihat Samhita by Varahamihira (6th century CE). This text categorizes dreams by the time they occur — dreams in the first quarter of the night are least significant, while dreams near dawn are most prophetic. Modern sleep science confirms that late-night (4-6 AM) dreams are the most vivid and emotionally significant — exactly what Varahamihira suggested 1,500 years ago.\n\nThe Yoga Nidra tradition (dating to the Upanishads but systematized by Swami Satyananda Saraswati in the 1960s) is essentially Indian lucid dreaming. It's a practice of maintaining awareness during the transition between waking and sleeping — the "hypnagogic" state. Modern research at Harvard and Stanford has confirmed that Yoga Nidra practitioners show unique brain wave patterns: they maintain alpha waves (conscious awareness) while simultaneously producing delta waves (deep sleep). They're literally awake and asleep at the same time.\n\nThe ancient Indian insight was profound: consciousness isn't binary (on/off). It's a spectrum. Dreams aren't mere noise — they're a distinct mode of awareness that reveals aspects of the mind invisible during waking life. Western neuroscience is now arriving at the same conclusion from a different direction.`
    },
  ],

  'first-tech-interview': [
    {
      id: 'mindset',
      title: 'The Interview Mindset Shift',
      type: 'story',
      body: `Here's the truth nobody tells nervous freshers: an interview is not an exam. It's a conversation. The interviewer isn't trying to catch you being wrong — they're trying to find out if you can think, communicate, and learn. Most rejections don't happen because the candidate didn't know a data structure. They happen because the candidate couldn't explain their thinking.\n\nThe biggest mindset shift: you're not begging for a job. You're evaluating a potential workplace. Does this company value learning? Will you grow here? Is the team culture healthy? When you interview with this mindset, your body language changes, your voice changes, and you naturally come across as more confident. Interviewers notice immediately.\n\nAnother myth: you need to know everything. No one does. The difference between getting an offer and getting rejected is often: "I don't know the answer, but here's how I would approach figuring it out" vs. "I don't know." The first response shows problem-solving ability. The second shows a dead end.\n\nThe most underrated interview skill is active listening. Many candidates are so anxious about their next answer that they don't fully hear the question. They answer what they prepared, not what was asked. Slow down. Repeat the question in your own words: "So you're asking me to design a URL shortener — let me clarify the requirements first." That ten-second pause signals maturity.`
    },
    {
      id: 'preparation',
      title: 'The 30-Day Prep Plan',
      type: 'deep-dive',
      body: `Week 1: Foundations. Revise core data structures — Arrays, Linked Lists, Stacks, Queues, Hash Maps, Trees, Graphs. Not theory — implement each one from scratch in your language of choice. If you can't write a linked list without googling, you're not ready yet.\n\nWeek 2: Patterns. LeetCode/HackerRank problems aren't random — they follow patterns. Focus on: Two Pointers, Sliding Window, BFS/DFS, Binary Search, Dynamic Programming (start with Fibonacci and Knapsack). Solve 5 problems per pattern. Understand the pattern, not the specific problem.\n\nWeek 3: System Design + Projects. Even for freshers, interviewers ask basic design questions: "How would you design a URL shortener?" or "How would you build a chat application?" Learn the building blocks: load balancers, databases (SQL vs NoSQL), caching (Redis), queues (Kafka). Prepare 2-3 projects with clear explanations of architecture decisions.\n\nWeek 4: Mock Interviews + HR Prep. Practice with a friend over video call. Time yourself. Record it. Watching yourself interview is painful but transformative — you'll catch filler words ("basically," "like," "umm"), nervous habits, and unclear explanations. Prepare answers for: Tell me about yourself (60 seconds), Why this company? (genuine reason), Biggest challenge you faced (STAR format: Situation, Task, Action, Result).\n\nDaily: 30 minutes of DSA practice + 30 minutes of reading about the company/role you're applying to. Consistency beats intensity.`
    },
    {
      id: 'rounds',
      title: 'What Happens in Each Round',
      type: 'comparison',
      body: `Round 1 — Resume Screening (automated or HR): Your resume gets 6 seconds of attention. Lead with projects, not education. Use numbers: "Built a REST API handling 500 requests/sec" beats "Built a REST API." Remove "proficient in MS Office" — it's 2026. Make sure your GitHub and LinkedIn URLs are clickable and lead to actual content.\n\nRound 2 — Technical/DSA (45-60 minutes): The interviewer gives you 1-2 coding problems. They're testing three things: Can you break the problem down? Can you code the solution? Can you analyze time/space complexity? Always start by talking through your approach BEFORE writing code. An interviewer wants to see your thought process, not just a working solution.\n\nRound 3 — System Design or Project Deep-Dive (for freshers, usually project-focused): The interviewer picks one project from your resume and drills deep. "Why did you use React instead of Vue?" "How would you handle 10x more users?" "What would you change if you rebuilt it?" There's no right answer — they want to see that you made conscious decisions, not that you followed a YouTube tutorial blindly.\n\nRound 4 — HR/Cultural Fit (30 minutes): Salary expectations (research Glassdoor/Levels.fyi first), relocation willingness, joining date, and behavioral questions. The "Tell me about a time you disagreed with a teammate" question is testing emotional intelligence, not conflict. Show that you listen, compromise, and focus on outcomes.`
    },
    {
      id: 'aha-moment',
      title: 'When They Actually Say Yes',
      type: 'zing-moment',
      body: `There's a moment in every interview where the interviewer shifts from testing you to selling you on the company. Their body language changes — they lean forward, start explaining the cool problems the team works on, ask about your interests beyond the resume. When this happens, you've effectively cleared the bar.\n\nBut here's the ZING moment that separates "callback" from "strong yes": it's the question YOU ask them. When the interviewer says "Do you have any questions for us?" — this is not a formality. This is your power move. Asking "What does the first 90 days in this role look like?" shows you're already visualizing yourself in the job. Asking "What's the biggest challenge the team is facing this quarter?" shows you think about impact, not just tasks.\n\nNever ask about salary in the technical round (save it for HR). Never ask things you could Google ("What does the company do?"). And never say "No, I'm good" — it signals disinterest.\n\nThe final truth: rejection is not failure. The average successful tech job hunt involves 30-50 applications, 5-10 first-round interviews, 2-3 final rounds, and 1-2 offers. Those numbers are normal. Every "no" is data. Was it DSA? Study more patterns. Was it communication? Practice mock interviews. Was it system design? Read "Designing Data-Intensive Applications." Track your rejections like a scientist, not an emotional being.`
    },
    {
      id: 'mistakes',
      title: '7 Mistakes That Kill Offers',
      type: 'resources',
      body: `Mistake 1: Not researching the company. If you can't name the company's main product or recent news, the interviewer feels disrespected. Spend 20 minutes on their website and LinkedIn before every interview.\n\nMistake 2: Jumping straight into code. Always clarify requirements, discuss edge cases, and talk through your approach first. Coding without a plan is like driving without navigation — you'll arrive somewhere, but probably not where you want to be.\n\nMistake 3: Lying about skills. If your resume says "Proficient in Kubernetes" and you can't explain what a pod is, the interview is over. Only list technologies you can discuss for at least 5 minutes with confidence.\n\nMistake 4: Poor communication during coding. An interviewer can't see your thought process. Narrate as you code: "I'm iterating through the array because we need to find the maximum..." Silence during coding is the #1 missed signal.\n\nMistake 5: Ignoring behavioral questions. "Tell me about a conflict" is not a trap — it's a chance to show self-awareness. Use the STAR format: Situation, Task, Action, Result. Prepare 3-4 stories that can adapt to any behavioral question.\n\nMistake 6: Not asking questions at the end. Shows zero curiosity about the role or team.\n\nMistake 7: Negotiating too early or too late. Don't discuss salary in Round 1. But DO negotiate when you get the offer letter — the first number is rarely the final number, especially in Indian startups. Research the range on levels.fyi, know your minimum, and negotiate confidently.`
    },
  ],

  'arthashastra-explained': [
    {
      id: 'chanakya',
      title: 'Who Was Chanakya?',
      type: 'story',
      body: `Chanakya (also called Kautilya or Vishnugupta) was born around 375 BCE into a Brahmin family in Takshashila (modern-day Taxila in Pakistan). He wasn't a king or a warrior — he was a teacher. But this teacher single-handedly destroyed the most powerful dynasty of his time and installed a new emperor on the throne of India.\n\nThe story goes: young Chanakya was humiliated in the court of the ruling Nanda dynasty. The Nanda king, Dhana Nanda, was arrogant, corrupt, and taxed the people mercilessly. Chanakya vowed to overthrow him. He found Chandragupta Maurya — a talented but unknown young man from a humble family — and spent years training him in statecraft, warfare, and administration.\n\nTheir story is the ultimate underdog tale: a teacher and a nobody versus the most powerful empire in India. Through brilliant strategy, spy networks, alliances, and military campaigns, Chanakya and Chandragupta dismantled the Nanda Empire and established the Mauryan Empire — which eventually became the largest empire in Indian history under Ashoka.\n\nChanakya then wrote the Arthashastra — a comprehensive manual for running a kingdom. It covers economics, law, military strategy, espionage, diplomacy, taxation, urban planning, and even how to manage government employees. It's not a philosophy book — it's a brutally practical operator's manual for power. Think of it as "How to Run a Country for Dummies," written by the most cunning political mind of the ancient world.`
    },
    {
      id: 'contents',
      title: 'The 15 Books of Arthashastra',
      type: 'deep-dive',
      body: `The Arthashastra is organized into 15 books, 150 chapters, and roughly 6,000 verses. Each book covers a specific aspect of statecraft.\n\nBooks 1-5 deal with internal administration: the training and discipline of the king, the appointment of ministers and advisors, the management of the treasury and tax collection, and the legal system. Chanakya's tax advice is remarkably modern — he recommends a tax rate of 1/6th to 1/4th of agricultural produce, argues that taxes should be proportional to income, and warns that over-taxation causes rebellion.\n\nBooks 6-10 cover war, diplomacy, and the famous "Mandala Theory" — Chanakya's framework for understanding inter-state relations. Foreign policy is broken into six strategies: peace (sandhi), war (vigraha), neutrality (asana), preparing for war (yana), alliance-seeking (samshraya), and the dual policy of peace with one and war with another (dvaidhibhava). No other ancient text categorizes international relations this precisely.\n\nBooks 11-15 cover espionage, secret agents, poisons, psychological warfare, and emergency management. Chanakya recommends maintaining a network of spies disguised as ascetics, merchants, students, and even courtesans. He describes methods for testing the loyalty of ministers using four temptations: dharma (duty), artha (wealth), kama (pleasure), and bhaya (fear). A minister who resists all four is truly loyal.\n\nWhat's stunning is the scope. This isn't a book about one topic — it's an entire operating system for civilization. The Arthashastra covers everything from the optimal city layout (with designated zones for different castes and trades) to the recommended salary for elephant caretakers.`
    },
    {
      id: 'mandala',
      title: "The Mandala Theory — India's Game of Thrones",
      type: 'zing-moment',
      body: `Here's the ZING moment: Chanakya proposed that in geopolitics, your immediate neighbor is naturally your enemy, your neighbor's neighbor is naturally your friend, and the pattern alternates outward like concentric circles — a "mandala" (circle). This theory, written 2,300 years ago, explains modern international relations with eerie accuracy.\n\nApply it to today: India and Pakistan (neighbors = rivals). India and Afghanistan (neighbor's neighbor = historically friendly). India and China (large neighbor = strategic competitor). India and Japan (China's neighbor = strong ally). Pakistan and China (India's rivals = each other's friends). The entire Indo-Pacific geopolitical chessboard follows Chanakya's mandala almost perfectly.\n\nBut Chanakya went deeper. He identified 12 types of kings in the mandala — the vijigishu (the ambitious conqueror, YOU), the ari (your enemy), the mitra (your friend), the ari-mitra (your enemy's friend), the mitra-mitra (your friend's friend), and so on. Each has a different strategy. It's like Game of Thrones, but with mathematical precision.\n\nThe Mandala Theory introduced the concept of "strategic depth" — the idea that real power comes not from the size of your army but from the strength and position of your alliances. NATO, QUAD, BRICS — all modern alliance frameworks operate on Mandala-like logic. Chanakya saw what took Western strategists another 2,000 years to figure out.`
    },
    {
      id: 'modern',
      title: 'Chanakya in Boardrooms and Elections',
      type: 'application',
      body: `The Arthashastra isn't a relic — it's a live playbook used in business schools and war colleges worldwide. Indian business leaders frequently cite Chanakya's principles. His concept of "Saam, Daam, Dand, Bhed" (negotiation, incentive, punishment, division) is taught in MBA programs as a negotiation framework.\n\nIn corporate strategy: Saam = building relationships (networking, charm). Daam = offering value (salary negotiation, partnership terms). Dand = demonstrating consequences (legal action, competition). Bhed = exploiting divisions (acquiring talent from competitors, leveraging market segments). Every business deal uses at least two of these.\n\nIndian elections are pure Arthashastra in action. Coalition politics (mandala theory), leader selection (choosing the right vijigishu), campaign strategy (combining Saam and Daam), opposition research (espionage chapter), and crisis management (Book 15) — Chanakya literally wrote the manual. Some political analysts argue that India's coalition era (1996-2014) was the purest real-world demonstration of Mandala Theory.\n\nEven Silicon Valley has noticed. Amazon's leadership principles — "Ownership," "Earn Trust," "Deliver Results" — echo Chanakya's advice on minister selection. Chanakya wrote: "A king must judge advisors not by their words but by the results of their actions." Jeff Bezos would agree.`
    },
    {
      id: 'ethics',
      title: 'The Moral Dilemma — When Does Strategy Become Immoral?',
      type: 'philosophy',
      body: `The Arthashastra is brutally honest about power, and that honesty makes many people uncomfortable. Chanakya advocates the use of spies, deception, poisons, and even assassination when the state's survival is at stake. He writes: "A king who does not take action against threats will be destroyed, like an untreated disease."\n\nThis raises a deep ethical question: is there a line between pragmatic leadership and moral bankruptcy? Chanakya's answer is nuanced. He distinguishes between defending the kingdom (justified) and gratuitous cruelty (unjustified). He insists that the king's personal pleasures must never override dharma — the welfare of the people. "In the happiness of the subjects lies the happiness of the king."\n\nCompare this with Machiavelli's The Prince (1513 CE), written 1,800 years later. Machiavelli says: "It is better to be feared than loved." Chanakya says: "The king should be feared by the wicked and loved by the good." The distinction is subtle but important — Chanakya's feared leader still serves the people; Machiavelli's just serves himself.\n\nModern ethics often presents a false binary: either you're moral or you're strategic. Chanakya rejects this. He argues that a ruler who doesn't protect the state out of moral squeamishness is actually MORE immoral — because millions suffer when leadership fails. This is the Arthashastra's hardest teaching: sometimes doing the right thing for many requires doing a hard thing for a few. India's nuclear policy ("no first use") and its surgical strikes both reflect this Chanakyan balance between restraint and action.`
    },
  ],

  'photosynthesis-explained': [
    {
      id: 'why-green',
      title: 'Why Are Plants Green?',
      type: 'story',
      body: `Plants are green because of a pigment called chlorophyll — but the real question is: why green? Sunlight contains all colors of the visible spectrum (red, orange, yellow, green, blue, violet). Chlorophyll absorbs red and blue light very efficiently but reflects green light. That reflected green light is what reaches your eyes, making leaves look green.\n\nBut here's the twist: green light actually carries significant energy at Earth's surface. So why do plants reject this energetic wavelength? One theory (called the "purple Earth hypothesis") suggests that billions of years ago, the first photosynthetic organisms used retinal (a purple pigment) that absorbed green light. When chlorophyll-based organisms evolved later, green light was already "taken" — so they adapted to use what was available: red and blue.\n\nAnother explanation is practical: absorbing ALL wavelengths would overheat the leaf. By reflecting green, plants avoid thermal damage during peak sunlight. It's like wearing a white shirt in summer instead of black — strategic rejection of energy you can't safely handle.\n\nThis is why leaves change color in autumn. As chlorophyll breaks down, it reveals the carotenoids (yellow/orange pigments) and anthocyanins (red/purple pigments) that were always there, hidden behind the dominant green. The colors of fall were always inside the leaf — you just couldn't see them through the chlorophyll.`
    },
    {
      id: 'mechanism',
      title: 'The Two-Stage Process',
      type: 'deep-dive',
      body: `Photosynthesis happens in two stages, both occurring inside chloroplasts — tiny organelles in leaf cells, each containing stacks of membrane-bound compartments called thylakoids.\n\nStage 1: Light Reactions (in thylakoid membranes). Sunlight hits chlorophyll, exciting electrons to a higher energy state. These energized electrons pass through a chain of proteins (the "electron transport chain"), and the energy released is used to pump hydrogen ions across the membrane, creating a gradient. This gradient drives an enzyme called ATP synthase to produce ATP (energy currency). Simultaneously, water molecules are split (photolysis): 2H2O becomes O2 + 4H+ + 4e-. The oxygen is released as a waste product — the very oxygen we breathe.\n\nStage 2: Calvin Cycle (in stroma — the fluid around thylakoids). This stage doesn't need light directly — it uses the ATP and NADPH produced in Stage 1 to "fix" CO2 into glucose. The enzyme RuBisCO (the most abundant protein on Earth!) grabs CO2 from the air and attaches it to a 5-carbon sugar. Through a series of reactions, a 3-carbon molecule (G3P) is produced. Two molecules of G3P combine to make one glucose molecule (C6H12O6).\n\nThe overall equation: 6CO2 + 6H2O + light energy gives C6H12O6 + 6O2. Six molecules of carbon dioxide plus six molecules of water, powered by sunlight, produce one glucose and six molecules of oxygen. This single equation sustains virtually all life on Earth.`
    },
    {
      id: 'equation',
      title: 'The Most Beautiful Equation in Biology',
      type: 'zing-moment',
      body: `6CO2 + 6H2O + light energy gives C6H12O6 + 6O2.\n\nRead it again. This equation is running right now in every green leaf on the planet — in the tree outside your window, in the seaweed at the bottom of the ocean, in the moss growing on a rock in Meghalaya. It ran during the age of dinosaurs. It will run after we're all gone. This equation literally built the atmosphere you're breathing.\n\nHere's the ZING moment: photosynthesis removes approximately 120 billion tons of CO2 from the atmosphere every year and replaces it with oxygen. Without it, Earth's atmosphere would become unbreathable in about 2,000 years. Every breath you take is a debt to a green leaf somewhere.\n\nBut here's what makes it even more incredible: this process is astonishingly efficient in terms of physics but terribly inefficient in terms of engineering. Only about 3-6% of the sunlight energy that hits a leaf actually gets converted to chemical energy (glucose). Human-made solar panels now achieve 20-25% efficiency. So why haven't we replaced photosynthesis with something better? Because photosynthesis does something solar panels can't: it builds itself. A leaf grows from a tiny seed, repairs itself, reproduces, and decomposes back into nutrients — a self-manufacturing, self-maintaining, biodegradable solar factory.\n\nEvolution didn't optimize for peak efficiency — it optimized for resilience and reproduction. And that's a lesson worth learning beyond biology.`
    },
    {
      id: 'types',
      title: 'C3 vs C4 vs CAM Photosynthesis',
      type: 'comparison',
      body: `Not all plants photosynthesize the same way. Evolution produced three variants, each adapted to different climates.\n\nC3 plants (rice, wheat, soybean — about 85% of all plant species) use the standard Calvin Cycle. CO2 is directly fixed by RuBisCO into a 3-carbon compound. The problem: in hot, dry conditions, RuBisCO mistakenly grabs O2 instead of CO2 (a process called photorespiration), wasting up to 25% of the plant's energy. C3 plants are most efficient in cool, moist environments.\n\nC4 plants (sugarcane, maize, sorghum) evolved a workaround. They fix CO2 in special "mesophyll" cells first, creating a 4-carbon compound, then shuttle it to inner "bundle sheath" cells where the Calvin Cycle runs. This creates a high concentration of CO2 around RuBisCO, virtually eliminating photorespiration. C4 plants thrive in hot, tropical conditions — which is why sugarcane grows in Maharashtra, not Himachal Pradesh.\n\nCAM plants (cactus, pineapple, agave) have the most creative solution. They open their stomata only at night (when it's cool and humid), absorb CO2, and store it as malic acid. During the day, they close their stomata to prevent water loss and use the stored CO2 for the Calvin Cycle. This allows them to survive in deserts where water is scarce.\n\nFor exams: C3 = most species, cool climates, photorespiration problem. C4 = tropical, efficient, 4-carbon intermediate. CAM = desert, nighttime CO2 uptake! Indian agriculture heavily depends on C3 (rice) and C4 (sugarcane) — knowing the difference is relevant to understanding crop yields under climate change.`
    },
    {
      id: 'future',
      title: 'Artificial Photosynthesis — The Next Green Revolution',
      type: 'discovery',
      body: `What if we could build machines that do what leaves do — convert sunlight and CO2 into fuel — but 10 times more efficiently? That's the dream of artificial photosynthesis, and it's closer to reality than you think.\n\nResearchers at Caltech and JNCASR (Jawaharlal Nehru Centre for Advanced Scientific Research, Bangalore) have built "artificial leaves" — thin devices that use sunlight to split water into hydrogen and oxygen. The hydrogen can be used as clean fuel or combined with CO2 to make methanol — a liquid fuel you can use in existing engines. Imagine a future where petrol pumps are replaced by fields of artificial leaves.\n\nIndia's Council of Scientific and Industrial Research (CSIR) labs are working on catalysts that mimic chlorophyll — using abundant metals like iron and cobalt instead of rare platinum. Making artificial photosynthesis cheap is the key to scaling it for a country of 1.4 billion people.\n\nThe implications are enormous. Artificial photosynthesis could: generate clean hydrogen fuel (replacing fossil fuels), remove CO2 from the atmosphere (fighting climate change), produce oxygen in space habitats (NASA is interested), and make food production independent of arable land. Scientists at the University of Chicago recently created "cyborg bacteria" — living bacteria coated in semiconductor nanoparticles that photosynthesize at 80% efficiency, compared to natural plants' 3-6%.\n\nThe first Green Revolution (1960s) used better crop varieties to feed India. The next Green Revolution might use artificial leaves to fuel it.`
    },
  ],

  'git-github-beginners': [
    {
      id: 'analogy',
      title: 'The Save Point Analogy',
      type: 'story',
      body: `Think of Git like save points in a video game. You're exploring a dungeon (writing code), and you reach a safe room (stable code). You save the game (git commit). Then you try a risky boss fight (experimental feature). If you die (the feature breaks everything), you reload the last save (git checkout) and try a different strategy. No progress lost.\n\nBut Git is even better than a game save because it keeps EVERY save point you've ever made. Want to see what your project looked like three weeks ago? Git remembers. Want to know who changed a specific line and why? Git knows. Want to undo one specific change from last month without affecting anything else? Git can do that.\n\nHere's where the analogy evolves: imagine playing the same game with 10 friends simultaneously. Each person is in their own parallel universe (branch) of the game, exploring different areas. When one person finds a treasure (builds a feature), they can merge their universe back into the main timeline. If two people modified the same room, Git helps them resolve the conflict.\n\nThis isn't just a metaphor — this is literally how software is built. Linux, the operating system running most of the world's servers, has thousands of developers working simultaneously on different branches. Git keeps all their work organized, tracked, and mergeable. Linus Torvalds (Linux's creator) built Git in 2005 because no existing tool could handle Linux's scale. A tool built to manage the world's largest open-source project is now used by every developer on Earth.`
    },
    {
      id: 'commands',
      title: 'The 7 Essential Commands',
      type: 'deep-dive',
      body: `These 7 commands cover 95% of what you'll do with Git daily:\n\n1. git init — Creates a new Git repository in your current folder. Run this once when starting a new project. It creates a hidden .git folder that tracks everything.\n\n2. git clone [URL] — Downloads an existing repository from GitHub/GitLab to your computer. This is how you get someone else's project.\n\n3. git add [files] — Stages your changes for the next commit. Think of it as putting items in a shopping cart before checkout. "git add ." adds ALL changed files. "git add index.js" adds just that one file.\n\n4. git commit -m "message" — Saves a snapshot of all staged changes with a description. The message should describe WHAT you changed and WHY. "Fix login bug where empty passwords were accepted" is good. "Updated stuff" is not.\n\n5. git push — Uploads your local commits to the remote repository (usually GitHub). This is how your code becomes visible to teammates. "git push origin main" pushes to the main branch.\n\n6. git pull — Downloads changes that others pushed and merges them into your local code. Always pull before starting work each day to stay updated.\n\n7. git checkout -b [name] — Creates a new branch and switches to it. Use branches for every new feature. "git checkout -b add-login-page" creates a safe space to work without affecting the main code.\n\nThat's it. Master these seven commands and you're ready for 95% of real-world development workflows.`
    },
    {
      id: 'branches',
      title: 'Branches — When It Finally Clicks',
      type: 'zing-moment',
      body: `Here's the ZING moment: a branch in Git is not a copy of your code. It's a pointer to a specific commit. Creating a branch is instant and takes almost zero disk space. This changes how you think about experimentation.\n\nWithout branches, development looks like this: everyone edits the same code, someone's half-finished feature breaks the main app, and the team enters "it was working yesterday" chaos. With branches, each developer works in their own isolated timeline. The main branch is always stable, deployable, and clean.\n\nThe typical workflow: you're on the "main" branch (stable production code). You want to add a dark mode feature. Step 1: git checkout -b feature/dark-mode. Step 2: Write the code, test it, commit it — all on your branch. Step 3: Push the branch to GitHub. Step 4: Open a "Pull Request" (PR) on GitHub — this is a formal request saying "I want to merge my branch into main." Step 5: Your teammate reviews the code, suggests changes, approves it. Step 6: Merge the PR. Your branch's changes are now in main. Step 7: Delete the feature branch — it's served its purpose.\n\nThis workflow is called "GitHub Flow" and it's used by teams from 2 people to 2,000 people. The beauty of branches is that they make failure safe. If your dark mode experiment breaks everything? Just delete the branch. Main was never affected. This freedom to experiment without fear is what makes Git revolutionary — not the version tracking, but the psychological safety to try things.`
    },
    {
      id: 'workflow',
      title: 'Real Developer Workflow',
      type: 'hands-on',
      body: `Here's what a typical day looks like for a developer using Git:\n\nMorning: Open terminal. "git pull origin main" to get any changes teammates pushed overnight. Check Slack/Teams for any new PRs to review.\n\nPick a task from the sprint board. Create a branch: "git checkout -b fix/payment-timeout-error." Work on the fix. Make small, focused commits as you go — maybe 3-5 commits over a few hours.\n\nAfternoon: Push your branch: "git push origin fix/payment-timeout-error." Go to GitHub and open a Pull Request with a description: what you changed, why, how to test. Tag a reviewer. While waiting for review, pull up another teammate's PR and review their code.\n\nReview comes back with a suggestion: "Can you add a unit test for the retry logic?" You make the change on the same branch, commit, push. The PR updates automatically. Reviewer approves. You click "Merge." Done. Delete the branch.\n\nThe .gitignore file is crucial for real projects. It tells Git which files to ignore — node_modules/ (thousands of dependency files), .env (secret API keys), build/ (compiled output). NEVER commit node_modules or secrets to Git. Ever. This is a common beginner mistake that's embarrassing at best (huge repos) and dangerous at worst (leaked API keys).\n\nPro tip: set up Git hooks with Husky to auto-run tests before every push. This prevents broken code from ever reaching GitHub.`
    },
    {
      id: 'mistakes',
      title: 'Fixing Common Mistakes',
      type: 'resources',
      body: `"I committed something I shouldn't have." Use "git reset --soft HEAD~1" to undo the last commit but keep your changes. If you already pushed, "git revert HEAD" creates a new commit that undoes the last one — safer than force-pushing.\n\n"I'm stuck in a weird state." The nuclear option: "git stash" saves your uncommitted changes to temporary storage, then "git checkout main" gets you back to safety. Later, "git stash pop" brings your saved changes back.\n\n"I accidentally committed to main instead of my branch." Don't panic. "git reset --soft HEAD~1" to undo the commit (keeps changes). "git checkout -b my-feature" to create the branch. "git add . && git commit" to commit there instead.\n\n"Merge conflict — what now?" Git creates conflict markers in the file. Open it, decide which version to keep (or combine both), remove the markers, then "git add" and "git commit." VS Code has a beautiful merge conflict UI that makes this visual.\n\n"I need to see what changed." "git log --oneline" shows commit history. "git diff" shows unstaged changes. "git diff --staged" shows staged changes. "git blame filename" shows who changed each line and when — incredibly useful for understanding legacy code.\n\n"I want to undo everything and start fresh." "git checkout -- ." discards all uncommitted changes. This is irreversible, so use it carefully. For a complete restart from remote: "git fetch origin && git reset --hard origin/main." Again, irreversible — make sure you understand what you're throwing away.`
    },
  ],

  'indian-monsoon-system': [
    {
      id: 'june-1',
      title: 'June 1st — When India Holds Its Breath',
      type: 'story',
      body: `Every year around June 1st, the India Meteorological Department (IMD) makes a single announcement that affects 1.4 billion people: "The monsoon has arrived in Kerala." It's the most anticipated weather update in the world — because for India, the monsoon isn't just weather. It's the economy, the food supply, and the mood of an entire nation.\n\nIndia's agricultural sector accounts for about 15% of GDP and employs over 40% of the workforce. Unlike developed nations where agriculture relies on irrigation infrastructure, roughly half of India's farmland depends entirely on monsoon rain. A good monsoon means a bumper crop, low food inflation, happy rural economy, and rising stock markets. A poor monsoon means drought, crop failure, farmer distress, and inflation that hits the poorest hardest.\n\nThe monsoon's arrival is dramatic. After months of scorching summer (April-May), when temperatures in central India regularly cross 45 degrees Celsius, suddenly the sky darkens, the wind shifts, and the first raindrops fall. The petrichor — that unique smell of dry earth absorbing rain — is so beloved in India that there's a perfume industry around it (mitti attar, made in Kannauj, UP). Bollywood has immortalized the monsoon in countless rain songs.\n\nBut the monsoon isn't just romantic — it's also catastrophic. Mumbai regularly floods when monsoon rain exceeds the city's drainage capacity. Kerala suffered devastating floods in 2018 and 2019. The same rain that feeds crops also destroys homes. India's relationship with the monsoon is love and fear in equal measure.`
    },
    {
      id: 'science',
      title: 'The Science — Pressure, Winds, and Mountains',
      type: 'deep-dive',
      body: `The Indian monsoon is driven by differential heating between land and ocean. Here's the mechanism:\n\nIn summer (April-June), the Indian landmass heats up much faster than the Indian Ocean. Hot air over land rises, creating a zone of low pressure (called the "monsoon trough") over northern India. The cooler, denser air over the Indian Ocean is at higher pressure. Basic physics: air flows from high pressure to low pressure. So moisture-laden winds rush from the ocean toward the land.\n\nThese winds cross the Equator (where the Coriolis effect deflects them), travel across the warm Indian Ocean (picking up enormous moisture), and hit India from the southwest — which is why it's called the Southwest Monsoon. The moisture-laden air first strikes the Western Ghats mountain range along India's west coast. As the air is forced to rise over the mountains, it cools, and water vapor condenses into clouds and rain — this is "orographic rainfall." This is why Mumbai, on the windward side of the Western Ghats, gets 2,400 mm of rain while Pune, just 150 km away on the leeward side, gets only 700 mm.\n\nThe Himalayas play a dual role: they block the monsoon winds from escaping northward into Central Asia (concentrating rainfall over the Indo-Gangetic plain) and they block cold Arctic air from entering India in winter. Without the Himalayas, India would have a climate more like the Sahara — hot, dry, and unforgiving.\n\nThe Inter-Tropical Convergence Zone (ITCZ) — where northern and southern hemisphere trade winds meet — shifts northward in summer, pulling the monsoon with it. Jet streams in the upper atmosphere also play a role: the Tropical Easterly Jet steers the monsoon toward India, while its position determines whether the monsoon will be strong or weak in a given year.`
    },
    {
      id: 'onset',
      title: 'The Moment Monsoon Arrives in Kerala',
      type: 'zing-moment',
      body: `The ZING moment of Indian geography: the Southwest Monsoon typically hits the Kerala coast on June 1st (plus or minus 7 days). From there, it races northward in two branches — the Arabian Sea branch (along the west coast) and the Bay of Bengal branch (up the east coast and into the Ganges valley).\n\nThe advance is remarkably predictable. Kerala: June 1. Mumbai: June 10-12. Delhi: June 25-28. All of India covered: July 15. The monsoon takes about 45 days to cover the entire country, advancing roughly 30-40 km per day. But some years it arrives late, stalls, or withdraws early — creating agricultural chaos.\n\nWhat makes the Kerala onset so significant is the burst of rainfall. After months of summer heat, the first monsoon rain isn't gentle — it arrives as a wall of water. Wind speeds increase, the sea turns rough, and fishing boats are recalled. Kerala's traditional "Edavapathi" rain (which arrives just before the true monsoon) often confuses people into thinking the monsoon has started early. IMD uses three strict criteria to declare monsoon onset: sustained rainfall over 2.5 mm across a minimum of 14 designated stations in Kerala, wind pattern shift, and depth of moisture in the atmosphere.\n\nThe monsoon's withdrawal is equally important. Starting around September 1, the monsoon retreats from northwest India first and south India last (by mid-October). The retreating monsoon picks up moisture from the Bay of Bengal and dumps it on Tamil Nadu — which is why Chennai's rainy season (October-December) is opposite to the rest of India. India has rainfall when everyone else is drying up, and vice versa.`
    },
    {
      id: 'types',
      title: 'Southwest vs Northeast Monsoon',
      type: 'comparison',
      body: `India experiences two monsoons. The Southwest Monsoon (June-September) provides 75% of India's total annual rainfall and is what people usually mean by "the monsoon." It originates from the Indian Ocean, enters India from the southwest, and affects the entire country. The mechanism: land is hotter than sea, so sea air rushes inland.\n\nThe Northeast Monsoon (October-December) is the return journey. As winter approaches, the land cools faster than the sea. Now the wind reverses — blowing from the cold northeast (from the Himalayas and Central Asia) toward the warmer ocean. These winds are mostly dry because they travel over land. BUT — when they cross the Bay of Bengal, they pick up moisture and hit Tamil Nadu's coast, giving Chennai its rainy season.\n\nThis is why Tamil Nadu is the odd one out: it's relatively dry during the Southwest Monsoon (it's on the leeward side of the Western Ghats) but gets heavy rain during the Northeast Monsoon. Chennai's devastating 2015 floods happened in December — peak Northeast Monsoon season.\n\nFor board exams, remember this table: Southwest Monsoon = June-September, enters from southwest, affects most of India, Arabian Sea + Bay of Bengal branches. Northeast Monsoon = October-December, enters from northeast, mainly affects Tamil Nadu and Andhra Pradesh, dry elsewhere. The "break monsoon" period (brief pause in July-August) is also important — it causes temporary dry spells during the main monsoon, often followed by intense rain bursts.\n\nEl Nino (warming of Pacific Ocean waters) typically weakens the Indian monsoon, while La Nina strengthens it. This teleconnection — Pacific Ocean temperatures affecting Indian rainfall — is one of the most important discoveries in monsoon science.`
    },
    {
      id: 'prediction',
      title: "How IMD Predicts Monsoon (And Why It's Hard)",
      type: 'discovery',
      body: `Predicting the Indian monsoon is one of the hardest problems in atmospheric science. It depends on ocean temperatures (Indian Ocean, Pacific Ocean, Atlantic Ocean), Himalayan snow cover, Eurasian land temperatures, stratospheric wind patterns, and dozens of other variables — many of which interact non-linearly. Small changes in one variable can cause massive shifts in rainfall.\n\nIMD uses a two-stage forecast. In April (before monsoon onset): a long-range statistical forecast based on 5 predictors — El Nino/La Nina index, Pacific Ocean sea surface temperatures, North Atlantic SST, Eurasian snow cover, and Indian Ocean Dipole. This forecast predicts whether total monsoon rainfall will be Normal (96-104% of long-period average), Above Normal, Below Normal, or Deficient.\n\nIn June (after onset): short-range forecasts using numerical weather prediction models. These are the "next 5 days" forecasts that use supercomputers to simulate the atmosphere mathematically. IMD uses its own models, plus data from global models (ECMWF/European, GFS/American). The accuracy improves every year but still struggles beyond 7 days.\n\nThe biggest challenge is spatial variability. Even in a "normal monsoon" year, some regions can face floods while others face drought — just 200 km apart. IMD's forecast of "normal rainfall for the country" is almost useless for a farmer in Vidarbha who needs to know if HIS district will get rain in the third week of July.\n\nIndia is investing heavily in improving prediction: the Monsoon Mission program has upgraded supercomputing capacity, ISRO's INSAT-3D satellite provides real-time cloud and moisture data, and new AI/ML models are being tested that can predict rainfall at the district level. The dream: hyper-local forecasts accurate enough to tell a Marathwada farmer exactly when to sow his seeds.`
    },
  ],
};

async function main() {
  console.log('⚡ Adding article body sections to all 10 topics...\n');

  for (const [slug, sections] of Object.entries(ARTICLE_SECTIONS)) {
    const topic = await prisma.topic.findUnique({ where: { slug } });
    if (!topic) {
      console.log(`⚠️  Topic "${slug}" not found, skipping`);
      continue;
    }

    const existingContent = (topic.content && typeof topic.content === 'object') ? topic.content as Record<string, unknown> : {};
    const updatedContent = {
      ...existingContent,
      sections, // Strategy 1 in ReadModeArticle: content.sections with .body
    };

    await prisma.topic.update({
      where: { slug },
      data: { content: updatedContent },
    });

    console.log(`✅ ${slug} — ${sections.length} sections added`);
  }

  console.log('\n⚡ Done! All topics now have full article body content.');
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
